---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-go-demo
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-go-demo-v1
  labels:
    app: vault-go-demo
    version: v1
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: vault-go-demo
      version: v1
  template:
    metadata: 
      name: vault-go-demo
      labels:
        app: vault-go-demo
        version: v1
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vault_go_demo"
        vault.hashicorp.com/agent-inject-secret-foo: "secret/test"
    spec:
      serviceAccountName: vault-auth
      automountServiceAccountToken: true
      containers:
        - name: vault-go-demo
          image: aklaas2/vault-go-demo-tokenization:latest
          ports:
          - containerPort: 9090
            protocol: TCP
